GaussianNB:
  class: revscoring.scoring.models.GaussianNB
  params: {}
BernoulliNB:
  class: revscoring.scoring.models.BernoulliNB
  params: {}
MultinomialNB:
  class: revscoring.scoring.models.MultinomialNB
  params:
  alpha: [0.1, 1, 10]
